### ISSUE TITLE
unrecognized arguments: --cpu_usage --memory_usage

### ISSUE THREAD

**Issue by CoralLeiCN** [gaogaotiantian/vizplugins#8]
Thanks for this great plugin for tracking the memory usage.

Got error with the example in **Basic Usage section**

`viztracer --plugin vizplugins --cpu_usage --memory_usage -- my_script.py`

**Error message**
python -m viztracer: error: unrecognized arguments: --cpu_usage --memory_usage

It works if `--` are replaced by `.`
`viztracer --plugin vizplugins.cpu_usage vizplugins.memory_usage  -- my_script.py`

**Versions / Dependencies**

Python version
> 3.10.9

viztracer 
> 0.16.0

vizplugins
> 0.1.3

**Comment by gaogaotiantian** [comment]
You are right. That's a typo. It should be ``viztracer --plugin "vizplugins --cpu_usage --memory_usage" -- my_script.py``. The quotes can't be omitted. Could you confirm this works? And do you want to make a PR to the docs? I can do it if you don't :)

**Comment by CoralLeiCN** [comment]
> viztracer --plugin "vizplugins --cpu_usage --memory_usage" -- my_script.py

It works. Thank you! I created a PR.

**Comment by gaogaotiantian** [comment]
Fixed by #9
